### ISSUE TITLE
Response to `GET` not being returned in re-used DHIS2 job

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/logical-outcomes#6]
After running this `GET` request, the response is not being passed to the rest of the job... not sure why because we had this working in another DHIS2 demo. 
https://github.com/OpenFn/logical-outcomes/blob/1e6b60545ed2d1a398ac9ffa5bdd424e468bc643/demo/upsertTrackedEntity.js#L6-L19

See L5 in run where nothing is returned for `rows`: https://www.openfn.org/projects/1765/runs/10719201

However - when I run this GET on Postman, see here for the response that includes data in `rows[0]`: https://github.com/OpenFn/logical-outcomes/blob/master/sample_data/getResponse.json

Here's an old demo job that I was re-using: https://github.com/OpenFn/logical-outcomes/blob/master/tnc/CSVtoDHIS2__http.js

## state
See LP for `Logical Outcomes DHIS2 Training`
Use this: https://github.com/OpenFn/logical-outcomes/blob/master/sample_data/csvRow.json

## adaptor
`language-http`

## To test
Re-run this: https://www.openfn.org/projects/1765/runs/10719201

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this is sorted. there were three things going on:
1. the new DHIS2 api version uses different URLs: https://github.com/OpenFn/logical-outcomes/commit/eac7996ff4ec6ce4387ce84ee4ece5e2af871293
2. an expression, rather than a function was passed for `query`, but in this job there was also an alterState, so that expression was evaluated _before_ the alterState... see that big slack issue from a few days ago (https://github.com/OpenFn/logical-outcomes/commit/61e7256a8af63ae2b7b7a590c4617eec6bd68dcc)
3. the new dhis2 api returns a `trackedEntityInstance` object, this job was built expecting an array of "rows".

Very excited to have @chaiwa-berian working on the new dhis2 adaptor version :-)

**Comment by aleksa-krolls** [comment]
@chaiwa-berian Is there any way to update the logs to show what has been updated in DHIS2. I see green checks in OpenFn, but from I have no idea whether a TEI was successfully created... nor do I know where to look in DHIS2 to verify whether this upload was successful: https://www.openfn.org/projects/1765/runs/10724705
