### ISSUE TITLE
Fix upsertTEI(...) for client demo

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/logical-outcomes#8]
## Request
The client was hoping to demo a quick DHIS2 `TrackedEntity` update this morning, but I can't get the DHIS2 adaptor functions to work. @chaiwa-berian can you please look at this first thing in the morning? We need to get this job working so that it will update this TEI below...
https://dev.piirs.care.org/dhis-web-tracker-capture/index.html#/dashboard?tei=J7t4VZTgb1N&program=SHRBw9XXHFk&ou=gixv5Y8nbzp

Current run failure: https://www.openfn.org/projects/p5qam9/runs/rn5krzey
```
Upserting tracked entity instance of type 'undefined' to org unit 'undefined' with undefined attributes and undefined enrollments.
Error: getaddrinfo ENOTFOUND null
```

## state
See LP for `LO DHIS2 - CARE Dev PIIRS`. 
No state needed right now... all values are hard-coded in the expression. 

## expression.js
Job: https://www.openfn.org/projects/p5qam9/jobs/jv9njn (I've configured it as a timer-job, so you can click the "play" button to re-run on production as needed)
```
upsertTEI(
  'aX5hD4qUpRW', //piirs uid
  {
    trackedEntityType: 'bsDL4dvl2ni',
    orgUnit: 'gixv5Y8nbzp',
    attributes: [
      {
        attribute: 'aX5hD4qUpRW',
        value: '007249ZWE',
      },
      {
        attribute: 'MxQPuS9G7hh',
        value: 'Regional',
      },
    ],
  }
);
```

## output
 Update this TEI below to change the `Geographical Scope` value to `Regional` (it's currently set to `Sub-National`). 
https://dev.piirs.care.org/dhis-web-tracker-capture/index.html#/dashboard?tei=J7t4VZTgb1N&program=SHRBw9XXHFk&ou=gixv5Y8nbzp

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this looks good. See slack: getting a standard `TrackedEntityAttribute with id aX5hD4qUpRW could not be found.` error, likely because that entity attribute doesn't exist. going to poke around a little more to see if i can verify that, but i think this is "done" in that georgi will need to enter a valid ID here.

**UPDATE**: Sure enough, I couldn't find a `TrackedEntityAttribute` with that id... maybe he wants this one: https://dev.piirs.care.org/dhis-web-maintenance/index.html#/edit/programSection/trackedEntityAttribute/SgQW3vpnhuL ?

attribute id : `SgQW3vpnhuL`

**Comment by taylordowns2000** [comment]
Using `SgQW3vpnhuL` fixed this issue, note that there will probably be a different attribute ID for this same custom attribute in any other dhis2 instance.
